// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEFphTUKug-SLDIgo1pnpNkxTGHNpkCWE',
    appId: '1:638628601654:web:0cca1dc52c7d0911a3dd97',
    messagingSenderId: '638628601654',
    projectId: 'project-bugkill',
    authDomain: 'project-bugkill.firebaseapp.com',
    storageBucket: 'project-bugkill.appspot.com',
    measurementId: 'G-M0RE5JEBK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm5do226yOLYrG2XNIYDnw5_1n1N7t4zk',
    appId: '1:638628601654:android:9316c865179fa24ea3dd97',
    messagingSenderId: '638628601654',
    projectId: 'project-bugkill',
    storageBucket: 'project-bugkill.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCP4Wlo9DIZA6LSLDOjL7XjG8iXZuIQNtY',
    appId: '1:638628601654:ios:749c517dbe3e9370a3dd97',
    messagingSenderId: '638628601654',
    projectId: 'project-bugkill',
    storageBucket: 'project-bugkill.appspot.com',
    iosClientId: '638628601654-64rh022js711b9110o0rfb7u86tabtdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectBugkill',
  );
}
